Update require-checklist.yml

diff --git a/.github/workflows/require-checklist.yml b/.github/workflows/require-checklist.yml
--- a/.github/workflows/require-checklist.yml
+++ b/.github/workflows/require-checklist.yml
@@ -1,14 +1,28 @@
-name: Require Checklist
+name: Checklist Validation
+
 on:
   pull_request:
     types: [opened, edited, synchronize]
-  issues:
-    types: [opened, edited, deleted]
+
 jobs:
-  job1:
-    runs-on: ubuntu-16.04
+  checklist:
+    runs-on: ubuntu-latest
+
     steps:
-      - uses: mheap/require-checklist-action@v1
-        with:
-          requireChecklist: false # If this is true and there are no checklists detected, the action will fail
-        
+    - name: Check Checklist
+      run: |
+        checklist=$(curl -s "${{ github.event.pull_request.url }}/files" | jq -r '.[] | select(.filename == "PULL_REQUEST_TEMPLATE.md") | .raw_url')
+        checklist_content=$(curl -s $checklist)
+
+        # Define the regex pattern to match checklist items
+        pattern="- \[([xX\s])\] (.*)"
+
+        # Check if each checklist item is marked as completed
+        while IFS= read -r line; do
+          if [[ $line =~ $pattern ]]; then
+            if [[ ${BASH_REMATCH[1]} != "x" && ${BASH_REMATCH[1]} != "X" ]]; then
+              echo "::error::Uncompleted checklist item: ${BASH_REMATCH[2]}"
+              exit 1
+            fi
+          fi
+        done <<< "$checklist_content"
