Update require-checklist.yml

diff --git a/.github/workflows/require-checklist.yml b/.github/workflows/require-checklist.yml
--- a/.github/workflows/require-checklist.yml
+++ b/.github/workflows/require-checklist.yml
@@ -19,18 +19,22 @@ jobs:
     - name: List Root Directory Contents
       run: ls -la
       
-    #- name: Checklist for developers
-     # run: |
-      #  cat /home/runner/work/skills-copilot-codespaces-vscode/PULL_REQUEST_TEMPLATE.md
-    
-    #- name: Check if all checkboxes are checked
-     # run: |
-      #  unchecked_items=$(grep -oP '\[ \]\s+\K.+' PULL_REQUEST_TEMPLATE.md | sed '/^$/d' || true)
-        
-       # if [ -n "$unchecked_items" ]; then
-        #  echo "::error::The following checklist items are unchecked:"
-         # echo "$unchecked_items"
-          #exit 1
-        #else
-         # echo "All checklist items are checked."
-        #fi
+    - name: Check Checklist
+      run: |
+        # Retrieve the content of PULL_REQUEST_TEMPLATE.md
+        template_url="${{ github.event.pull_request.url }}/files"
+        checklist_content=$(curl -s $template_url | jq -r '.[] | select(.filename == "PULL_REQUEST_TEMPLATE.md") | .raw_url')
+        template_content=$(curl -s $checklist_content)
+
+        # Define the regex pattern to match checklist items
+        pattern="- \[([xX\s])\] (.*)"
+
+        # Check if each checklist item is marked as completed
+        while IFS= read -r line; do
+          if [[ $line =~ $pattern ]]; then
+            if [[ ${BASH_REMATCH[1]} != "x" && ${BASH_REMATCH[1]} != "X" ]]; then
+              echo "::error::Uncompleted checklist item: ${BASH_REMATCH[2]}"
+              exit 1
+            fi
+          fi
+        done <<< "$template_content"
